// Package file data.
const packageJson = (name) => ({
  name: `${name}`,
  version: "1.0.0",
  description: "This is NodeJS API generated by nodejs-api-cli",
  main: "src/index.js",
  scripts: {
    start: "babel-node src/index.js",
    test:
      "nyc --reporter=text mocha tests/**/*.js --require @babel/register --exit",
    "create:db": "babel-node src/scripts/createTables.js",
    "drop:db": "babel-node src/scripts/dropdb.js",
    fix: "standard --fix",
  },
  repository: {
    type: "git",
    url: "",
  },
  keywords: ["nodejs", "api", "nodejs-api-cli"],
  author: "",
  license: "ISC",
  babel: {
    presets: [
      [
        "@babel/preset-env",
        {
          targets: {
            node: "current"
          }
        }
      ]
    ]
  }
});

module.exports = packageJson;
